-- v0.2.0: Add route support
-- Note: The route_hops column is now added programmatically in ensureSchema()
-- in db.go to handle idempotent migrations. This file is kept for reference.
-- No SQL operations needed here.